-- KEYBOARD SETTINGS CONTROLS
SETTINGS_NAV_UP = "w"
SETTINGS_NAV_DOWN = "s"
SETTINGS_NAV_LEFT = "a"
SETTINGS_NAV_RIGHT = "d"

SETTINGS_NAV_SELECT = "return"
SETTINGS_NAV_CALIBRATE_LEFT = "left"
SETTINGS_NAV_CALIBRATE_RIGHT = "right"
