-- SCENE INDICES
MENU_INDEX = 0
GAMEPLAY_INDEX = 1
SETTINGS_INDEX = 2

-- Unchangeable key binds
-- KEYBOARD MENU CONTROLS
MENU_TO_GAMEPLAY = "p"
MENU_TO_SETTINGS = "s"

-- KEYBOARD GAMEPLAY CONTROLS
GAMEPLAY_PAUSE = "escape"

-- KEYBOARD SETTINGS CONTROLS
SETTINGS_NAV_UP = "w"
SETTINGS_NAV_DOWN = "s"
SETTINGS_NAV_LEFT = "a"
SETTINGS_NAV_RIGHT = "d"

SETTINGS_NAV_SELECT = "return"
SETTINGS_NAV_CALIBRATE_LEFT = "left"
SETTINGS_NAV_CALIBRATE_RIGHT = "right"
